#**Generative AI - Text Generation and Machine**
Translation

1. What is Generative AI and what are its primary use cases across
industries?

   - Generative AI is a branch of artificial intelligence that creates new content—such as text, images, audio, video, code, and designs—by learning patterns from existing data. Unlike traditional AI, which mainly analyzes or classifies information, Generative AI produces original outputs based on user prompts.

      Primary Use Cases Across Industries:

        - Healthcare: Medical documentation, drug discovery, diagnostic support, and patient assistance.
        - Education: Personalized learning, content creation, tutoring, and assessment generation.
        - Software Development: Code generation, debugging, testing, and documentation.

        - Marketing: Content creation, ad copy, email campaigns, and social media posts.
        - Finance: Report generation, fraud detection support, risk analysis, and customer service.
        - Retail & E-commerce: Product recommendations, product descriptions, and customer support.
        - Manufacturing: Product design, predictive maintenance, and process optimization.
        - Media & Entertainment: Creating articles, images, videos, music, and game content.
        - Customer Service: AI chatbots and virtual assistants for 24/7 support.

Conclusion:
          Generative AI enhances creativity, automates repetitive tasks, improves productivity, and enables faster decision-making across various industries.

2. Explain the role of probabilistic modeling in generative models. How do
these models differ from discriminative models?

      - Role of Probabilistic Modeling in Generative Models:

           Probabilistic modeling is the foundation of generative models. It enables the model to learn the probability distribution of the data, allowing it to generate new samples that resemble the training data. Instead of memorizing examples, the model estimates how likely different data patterns are and then creates new data based on those probabilities.

           For example, a generative model trained on handwritten digits can generate new digit images that look realistic but were never seen during training.

           Key Roles:

           - Learns the underlying data distribution.
           - Generates new and realistic data samples.
           - Handles uncertainty and variability in data.
           - Supports tasks such as image generation, text generation, speech synthesis, and data augmentation.


          # Difference Between Generative and Discriminative Models

          # Generative Models

          - Learn the joint probability distribution P(X, Y) or data distribution P(X).
          - Can generate new data samples.
          - Focus on how the data is generated.
          - Used for content generation and unsupervised learning.
          - Examples: GANs, VAEs, GPT, Diffusion Models.


          # Discriminative Models

          - Learn the conditional probability P(Y|X).
          - Cannot generate new data; only classify or predict.
          - Focus on distinguishing between classes.
          - Used mainly for classification and prediction tasks.
          - Examples: Logistic Regression, Support Vector Machine (SVM), Decision Trees, Neural Network Classifiers.




          Conclusion - Probabilistic modeling allows generative models to understand the underlying data distribution and create realistic new content. In contrast, discriminative models focus on learning the relationship between inputs and outputs to make accurate predictions or classifications, without generating new data.

3.  What is the difference between Autoencoders and Variational
Autoencoders (VAEs) in the context of text generation?

    # Autoencoders (AEs)

      - Compress input text into a fixed latent representation and reconstruct it.
      - Produce a deterministic latent vector.
      - Mainly used for text compression, denoising, and feature extraction.
      - Cannot easily generate diverse new text.
      - Simpler architecture and easier to train.


      # Variational Autoencoders (VAEs)

      - Learn a probability distribution in the latent space and generate new text by sampling from it.
      - Produce a probabilistic latent representation (mean and variance).
      - Mainly used for text generation, sentence completion, and data augmentation.
      - Can generate diverse and realistic text samples.
      - More complex due to probabilistic sampling and additional loss function (KL divergence).

4. Describe the working of attention mechanisms in Neural Machine
Translation (NMT). Why are they critical?

      - Attention Mechanism in Neural Machine Translation (NMT):

           The attention mechanism allows an NMT model to focus on the most relevant words in the source sentence while generating each word in the target sentence. Instead of relying on a single fixed-length context vector, the decoder dynamically attends to different parts of the input sequence at every decoding step.

           Working of Attention
           - Encoding: The encoder processes the input sentence and produces a hidden state for each input word.
           - Attention Score: For each target word, the decoder calculates attention scores between its current state and all encoder hidden states.
           - Context Vector: A weighted sum of the encoder hidden states is computed to form a context vector.
           - Word Generation: The decoder uses the context vector along with its previous state to generate the next target word.
           - Repeat: This process continues until the entire translated sentence is generated


           Why is Attention Critical?
             
          Handles long sentences by avoiding the limitations of a fixed-length context vector.
          Improves translation accuracy by focusing on the most relevant source words.
          Captures long-range dependencies between words in a sentence.

5. What ethical considerations must be addressed when using generative AI
for creative content such as poetry or storytelling?

      - When using Generative AI for creative content like poetry or storytelling, several ethical issues must be considered to ensure responsible and fair use.

      - Ethical Considerations
          
          - Copyright and Intellectual Property =
            AI-generated content should not infringe on copyrighted works or closely copy existing authors' creations.
          - Plagiarism =
            The generated content should be original and should not reproduce someone else's work without permission or attribution.
          - Transparency =
            It should be disclosed when content is created or significantly assisted by AI, especially in publishing or competitions.
          - Bias and Fairness =
            AI models may reflect biases present in their training data. Outputs should be reviewed to avoid stereotypes or discriminatory content.
          - Misinformation =
            AI-generated stories or poems should not be presented in ways that intentionally mislead people or spread false information.       
          - Privacy =
            AI should not generate content that reveals or misuses personal or confidential information.
          - Accountability =
            Human users remain responsible for reviewing and editing AI-generated content before publication.
          - Respect for Cultural and Social Values =
            Content should avoid offensive, harmful, or culturally insensitive language and themes.

6.  Use the following small text dataset to train a simple Variational
Autoencoder (VAE) for text reconstruction:
["The sky is blue", "The sun is bright", "The grass is green",
"The night is dark", "The stars are shining"]
   
    1.Preprocess the data (tokenize and pad the sequences).
     
   2. Build a basic VAE model for text reconstruction.
   3. Train the model and show how it reconstructs or generates similar sentences.
Include your code, explanation, and sample outputs.
(Include your Python code and output in the code box below.)

      - This is a programming assignment, so below is a complete example using TensorFlow/Keras. Since the dataset is extremely small (5 sentences), the VAE will not generate high-quality text. The purpose is to demonstrate the implementation.


In [8]:
# ==========================================
# SIMPLE TEXT VAE (Google Colab Working)
# ==========================================

import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# -----------------------------
# Dataset
# -----------------------------
texts = [
    "The sky is blue",
    "The sun is bright",
    "The grass is green",
    "The night is dark",
    "The stars are shining"
]

# -----------------------------
# Preprocessing
# -----------------------------
tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)

seqs = tokenizer.texts_to_sequences(texts)

max_len = max(len(i) for i in seqs)

X = pad_sequences(seqs, maxlen=max_len, padding="post")

vocab_size = len(tokenizer.word_index) + 1

print("Vocabulary Size:", vocab_size)
print("Padded Sequences:\n", X)

# -----------------------------
# Parameters
# -----------------------------
embedding_dim = 16
latent_dim = 8

# -----------------------------
# Encoder
# -----------------------------
encoder_inputs = tf.keras.Input(shape=(max_len,))

x = tf.keras.layers.Embedding(vocab_size, embedding_dim)(encoder_inputs)
x = tf.keras.layers.Flatten()(x)
x = tf.keras.layers.Dense(32, activation="relu")(x)

z_mean = tf.keras.layers.Dense(latent_dim)(x)
z_log_var = tf.keras.layers.Dense(latent_dim)(x)

# Sampling Layer
class Sampling(tf.keras.layers.Layer):
    def call(self, inputs):
        z_mean, z_log_var = inputs
        epsilon = tf.random.normal(shape=tf.shape(z_mean))
        return z_mean + tf.exp(0.5 * z_log_var) * epsilon

z = Sampling()([z_mean, z_log_var])

encoder = tf.keras.Model(
    encoder_inputs,
    [z_mean, z_log_var, z],
    name="encoder"
)

# -----------------------------
# Decoder
# -----------------------------
latent_inputs = tf.keras.Input(shape=(latent_dim,))

x = tf.keras.layers.Dense(32, activation="relu")(latent_inputs)

x = tf.keras.layers.Dense(max_len * vocab_size)(x)

decoder_outputs = tf.keras.layers.Reshape((max_len, vocab_size))(x)

decoder = tf.keras.Model(latent_inputs, decoder_outputs, name="decoder")

# -----------------------------
# VAE Model
# -----------------------------
class VAE(tf.keras.Model):

    def __init__(self, encoder, decoder):
        super().__init__()
        self.encoder = encoder
        self.decoder = decoder

    def train_step(self, data):

        if isinstance(data, tuple):
            data = data[0]

        with tf.GradientTape() as tape:

            z_mean, z_log_var, z = self.encoder(data)

            reconstruction = self.decoder(z)

            reconstruction_loss = tf.reduce_mean(
                tf.keras.losses.sparse_categorical_crossentropy(
                    data,
                    reconstruction,
                    from_logits=True
                )
            )

            kl_loss = -0.5 * tf.reduce_mean(
                1 + z_log_var - tf.square(z_mean) - tf.exp(z_log_var)
            )

            total_loss = reconstruction_loss + kl_loss

        grads = tape.gradient(total_loss, self.trainable_variables)

        self.optimizer.apply_gradients(
            zip(grads, self.trainable_variables)
        )

        return {
            "loss": total_loss,
            "reconstruction_loss": reconstruction_loss,
            "kl_loss": kl_loss,
        }

vae = VAE(encoder, decoder)

vae.compile(optimizer="adam")

# -----------------------------
# Train
# -----------------------------
vae.fit(X, epochs=300, verbose=1)

# -----------------------------
# Reconstruction
# -----------------------------
print("\nReconstruction\n")

_, _, z = encoder.predict(X)

pred = decoder.predict(z)

pred_ids = np.argmax(pred, axis=-1)

reverse = {v:k for k,v in tokenizer.word_index.items()}

for i in range(len(X)):

    original = " ".join(
        reverse.get(id,"") for id in X[i] if id!=0
    )

    reconstructed = " ".join(
        reverse.get(id,"") for id in pred_ids[i] if id!=0
    )

    print("Original     :", original)
    print("Reconstructed:", reconstructed)
    print()

# -----------------------------
# Generate Similar Sentence
# -----------------------------
print("\nGenerated Sentence\n")

random_vector = np.random.normal(size=(1, latent_dim))

generated = decoder.predict(random_vector)

generated = np.argmax(generated, axis=-1)[0]

sentence = " ".join(
    reverse.get(id,"") for id in generated if id!=0
)

print(sentence)

Vocabulary Size: 14
Padded Sequences:
 [[ 1  3  2  4]
 [ 1  5  2  6]
 [ 1  7  2  8]
 [ 1  9  2 10]
 [ 1 11 12 13]]
Epoch 1/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 9s 9s/step - kl_loss: 9.4371e-04 - loss: 2.8151 - reconstruction_loss: 2.8141
Epoch 2/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 321ms/step - kl_loss: 0.0010 - loss: 2.7125 - reconstruction_loss: 2.7115
Epoch 3/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step - kl_loss: 0.0011 - loss: 2.7644 - reconstruction_loss: 2.7633
Epoch 4/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 251ms/step - kl_loss: 0.0012 - loss: 2.7388 - reconstruction_loss: 2.7376
Epoch 5/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - kl_loss: 0.0013 - loss: 2.7064 - reconstruction_loss: 2.7051
Epoch 6/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - kl_loss: 0.0014 - loss: 2.6831 - reconstruction_loss: 2.6817
Epoch 7/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - kl_loss: 0.0015 - loss: 2.7331 - reconstruction_loss: 2.7316
Epoch 8/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step - kl_loss: 0.0017 - loss: 2.6581 - 

7. Use a pre-trained GPT model (like GPT-2 or GPT-3) to translate a short
English paragraph into French and German. Provide the original and translated text.
(Include your Python code and output in the code box below.)

      - Below is a complete solution using the Hugging Face Transformers library with the GPT-2 model. (Note: GPT-2 is primarily a text generation model, so prompt-based translation works for demonstration purposes. Models specifically trained for translation generally perform better.)

In [ ]:
# ==========================================
# GPT-2 Translation (English → French/German)
# ==========================================

from transformers import pipeline

# Load GPT-2 text generation pipeline
generator = pipeline("text-generation", model="gpt2")

# Original English paragraph
text = "Artificial Intelligence is transforming the world by improving healthcare, education, and business."

# ---------- English to French ----------
prompt_fr = f"Translate the following English text to French:\n\n{text}\n\nFrench:"
result_fr = generator(
    prompt_fr,
    max_new_tokens=60,
    do_sample=False
)

# ---------- English to German ----------
prompt_de = f"Translate the following English text to German:\n\n{text}\n\nGerman:"
result_de = generator(
    prompt_de,
    max_new_tokens=60,
    do_sample=False
)

print("Original:")
print(text)

print("\nFrench Translation:")
print(result_fr[0]["generated_text"])

print("\nGerman Translation:")
print(result_de[0]["generated_text"])

Explanation
        - Model: GPT-2 (pre-trained language model).
        - Task: Prompt-based translation from English to French and German.
        - Input: An English paragraph.
        - Output: The paragraph translated into French and German.

8.  Implement a simple attention-based encoder-decoder model for
English-to-Spanish translation using Tensorflow or PyTorch.
(Include your Python code and output in the code box below.)
  
       - Below is a simple implementation of an Attention-based Encoder-Decoder (Seq2Seq) model for English-to-Spanish translation using TensorFlow/Keras. This example uses a very small dataset for demonstration purposes.

In [ ]:
# ============================================
# Attention-based Encoder-Decoder for
# English to Spanish Translation
# ============================================

import tensorflow as tf
from tensorflow.keras.layers import Input, Embedding, LSTM, Dense, Attention, Concatenate
from tensorflow.keras.models import Model
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

# -------------------------------
# Sample Dataset
# -------------------------------

english = [
    "hello",
    "how are you",
    "good morning",
    "thank you",
    "good night"
]

spanish = [
    "hola",
    "como estas",
    "buenos dias",
    "gracias",
    "buenas noches"
]

# -------------------------------
# Tokenization
# -------------------------------

eng_tokenizer = Tokenizer(filters='')
spa_tokenizer = Tokenizer(filters='')

eng_tokenizer.fit_on_texts(english)
spa_tokenizer.fit_on_texts(spanish)

encoder_input = eng_tokenizer.texts_to_sequences(english)
decoder_input = spa_tokenizer.texts_to_sequences(spanish)

max_eng = max(len(x) for x in encoder_input)
max_spa = max(len(x) for x in decoder_input)

encoder_input = pad_sequences(encoder_input, maxlen=max_eng, padding='post')
decoder_input = pad_sequences(decoder_input, maxlen=max_spa, padding='post')

encoder_vocab = len(eng_tokenizer.word_index) + 1
decoder_vocab = len(spa_tokenizer.word_index) + 1

# Decoder target
decoder_target = np.expand_dims(decoder_input, -1)

# -------------------------------
# Encoder
# -------------------------------

latent_dim = 64

encoder_inputs = Input(shape=(max_eng,))
enc_embed = Embedding(encoder_vocab, 64)(encoder_inputs)

encoder_outputs, state_h, state_c = LSTM(
    latent_dim,
    return_sequences=True,
    return_state=True
)(enc_embed)

# -------------------------------
# Decoder
# -------------------------------

decoder_inputs = Input(shape=(max_spa,))
dec_embed = Embedding(decoder_vocab, 64)(decoder_inputs)

decoder_outputs, _, _ = LSTM(
    latent_dim,
    return_sequences=True,
    return_state=True
)(
    dec_embed,
    initial_state=[state_h, state_c]
)

# -------------------------------
# Attention Layer
# -------------------------------

attention = Attention()
attention_output = attention([decoder_outputs, encoder_outputs])

concat = Concatenate(axis=-1)(
    [decoder_outputs, attention_output]
)

outputs = Dense(
    decoder_vocab,
    activation='softmax'
)(concat)

# -------------------------------
# Build Model
# -------------------------------

model = Model(
    [encoder_inputs, decoder_inputs],
    outputs
)

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

# -------------------------------
# Train
# -------------------------------

model.fit(
    [encoder_input, decoder_input],
    decoder_target,
    epochs=100,
    batch_size=2
)

# -------------------------------
# Prediction
# -------------------------------

prediction = model.predict(
    [encoder_input, decoder_input]
)

predicted = np.argmax(prediction, axis=-1)

reverse_index = {
    v:k for k,v in spa_tokenizer.word_index.items()
}

print("\nTranslations:\n")

for seq in predicted:
    words = []
    for token in seq:
        if token != 0:
            words.append(reverse_index.get(token, ""))
    print(" ".join(words))

Explanation
   - Dataset
     A small English–Spanish parallel corpus is created.
   - Preprocessing
   - Tokenize both English and Spanish sentences.
     Convert words to integer sequences.
     Pad sequences to equal length.
   - Encoder
     Uses an Embedding layer followed by an LSTM.


Note: Since the dataset contains only five sentence pairs, the model memorizes the training data. In real-world Neural Machine Translation, attention-based encoder-decoder models are trained on thousands or millions of bilingual sentence pairs for accurate translation.

9. Use the following short poetry dataset to simulate poem generation with a
pre-trained GPT model:
["Roses are red, violets are blue,",
"Sugar is sweet, and so are you.",
"The moon glows bright in silent skies,",
"A bird sings where the soft wind sighs."]
Using this dataset as a reference for poetic structure and language, generate a new 2-4
line poem using a pre-trained GPT model (such as GPT-2). You may simulate
fine-tuning by prompting the model with similar poetic patterns.
Include your code, the prompt used, and the generated poem in your answer.

   - Below is a complete example using GPT-2 from the Hugging Face Transformers library. Since the dataset is very small, we simulate fine-tuning by using the poems as part of the prompt.

In [ ]:
# ==========================================
# Poem Generation using Pre-trained GPT-2
# ==========================================

from transformers import pipeline

# Load GPT-2 model
generator = pipeline("text-generation", model="gpt2")

# Reference poetry dataset
poems = [
    "Roses are red, violets are blue,",
    "Sugar is sweet, and so are you.",
    "The moon glows bright in silent skies,",
    "A bird sings where the soft wind sighs."
]

# Prompt (simulating fine-tuning)
prompt = """
Use the following poetic style as inspiration:

Roses are red, violets are blue,
Sugar is sweet, and so are you.
The moon glows bright in silent skies,
A bird sings where the soft wind sighs.

Write a new 4-line poem in the same style:
"""

# Generate poem
result = generator(
    prompt,
    max_new_tokens=60,
    temperature=0.8,
    top_p=0.95,
    do_sample=True
)

print("Prompt:")
print(prompt)

print("\nGenerated Poem:\n")
print(result[0]["generated_text"])

Explanation

  - Model: GPT-2 (pre-trained language model)
  - Technique: Prompt-based poem generation (simulating fine-tuning)
  - Reference Dataset: Four short poetic lines are provided to guide the model's style.
  - Output: A new 4-line poem with a similar rhythm and poetic structure.

10. Imagine you are building a creative writing assistant for a publishing
company. The assistant should generate story plots and character descriptions using
Generative AI. Describe how you would design the system, including model selection,
training data, bias mitigation, and evaluation methods. Explain the real-world challenges
you might face.

    - A creative writing assistant should help authors generate story plots, character descriptions, dialogue, and writing ideas while maintaining originality, creativity, and ethical standards.
     
       - System Design

         The system consists of the following components:

         User Interface: Authors enter prompts such as genre, theme, setting, or character traits.
         Preprocessing: The prompt is cleaned and analyzed to identify keywords and writing style.

        - Model Selection

          The model should have strong language understanding and creative writing capabilities.
  
          Suitable models include:

          GPT-4 / GPT-4o – Excellent creativity and coherence.
          Llama 3 – Open-source and customizable.
          Mistral – Efficient with good text generation quality